name = "Gossamer"
grammar = "gossamer"
path_suffixes = ["gos"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>"
tab_size = 4

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
